# Generated by Django 5.2.16 on 2026-07-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_warning_sent_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('critical_warning', 'إنذار حرج - مهلة السداد'), ('auto_disconnect', 'فصل آلي - انتهاء المهلة')], default='critical_warning', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مشرف'), ('delegate', 'مندوب'), ('accountant', 'محاسب'), ('cashier', 'أمين المكتب')], max_length=20),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('processing', 'قيد المعالجة'), ('closed', 'مغلقة')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.student')),
            ],
            options={
                'db_table': 'complaints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('wallet_provider', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'قيد التحقق'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.room')),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
