# Generated by Django 5.2.16 on 2026-07-19 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notification_notification_type_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('not_configured', 'غير مهيأ')], default='not_configured', max_length=20),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_installments', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('defaulted', 'متعثرة'), ('cancelled', 'ملغاة')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_plans', to='api.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='api.room')),
            ],
            options={
                'db_table': 'installment_plans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('overdue', 'متأخر')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.installmentplan')),
            ],
            options={
                'db_table': 'installment_payments',
                'ordering': ['due_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManualMeterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('connect', 'توصيل'), ('disconnect', 'فصل')], max_length=20)),
                ('reason', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_meter_actions', to='api.room')),
            ],
            options={
                'db_table': 'manual_meter_actions',
                'managed': True,
            },
        ),
    ]
