# Generated by Django 5.2.16 on 2026-07-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_sms_status_installmentplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('manual_meter_action', 'إجراء يدوي للعداد'), ('installment_plan_created', 'إنشاء خطة تقسيط'), ('settle_payment', 'تسوية سداد'), ('system_settings_updated', 'تحديث إعدادات النظام'), ('auto_disconnect', 'فصل آلي للعداد'), ('critical_warning_sent', 'إرسال إنذار حرج')], max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
