# Generated by Django 5.2.16 on 2026-07-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='anomaly_threshold_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('manual_meter_action', 'إجراء يدوي للعداد'), ('installment_plan_created', 'إنشاء خطة تقسيط'), ('settle_payment', 'تسوية سداد'), ('system_settings_updated', 'تحديث إعدادات النظام'), ('auto_disconnect', 'فصل آلي للعداد'), ('critical_warning_sent', 'إرسال إنذار حرج'), ('anomaly_override', 'تجاوز تحذير الاستهلاك الشاذ')], max_length=50),
        ),
    ]
