# Generated by Django 5.2.16 on 2026-07-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemsettings_anomaly_threshold_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ الدفع الفعلي', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('manual_meter_action', 'إجراء يدوي للعداد'), ('installment_plan_created', 'إنشاء خطة تقسيط'), ('settle_payment', 'تسوية سداد'), ('system_settings_updated', 'تحديث إعدادات النظام'), ('auto_disconnect', 'فصل آلي للعداد'), ('critical_warning_sent', 'إرسال إنذار حرج'), ('anomaly_override', 'تجاوز تحذير الاستهلاك الشاذ'), ('financial_report_generated', 'إنشاء تقرير مالي')], max_length=50),
        ),
    ]
