# Generated by Django 5.2.16 on 2026-07-20 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_paid_at_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qr_code',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
