# Generated by Django on 2026-07-21 02:46

from django.db import migrations

def fix_buildings(apps, schema_editor):
    Building = apps.get_model('api', 'Building')
    
    # 1. First, let's look for "مبنى H" or any building containing "H"
    building_h = Building.objects.filter(name__icontains='H').first()
    if building_h:
        # Check if code '1' is already taken by someone else
        conflict = Building.objects.filter(code='1').exclude(id=building_h.id).first()
        if conflict:
            conflict.code = conflict.code + '_temp'
            conflict.save()
            
        building_h.name = 'مبنى A'
        building_h.code = '1'
        building_h.save()
    
    # 2. Look for "مبنى الطب" or any building containing "الطب"
    building_med = Building.objects.filter(name__icontains='الطب').first()
    if building_med:
        conflict = Building.objects.filter(code='2').exclude(id=building_med.id).first()
        if conflict:
            conflict.code = conflict.code + '_temp'
            conflict.save()
            
        building_med.name = 'مبنى B'
        building_med.code = '2'
        building_med.save()
        
    # If they don't exist by those names, let's just make sure we have A, B, C with 1, 2, 3
    # We will try to map existing buildings to A, B, C if they haven't been mapped
    all_buildings = list(Building.objects.all().order_by('id'))
    target_mappings = [
        ('مبنى A', '1'),
        ('مبنى B', '2'),
        ('مبنى C', '3')
    ]
    
    for i, b in enumerate(all_buildings):
        if i < 3:
            target_name, target_code = target_mappings[i]
            if b.name != target_name or b.code != target_code:
                # Handle unique constraint on code
                conflict = Building.objects.filter(code=target_code).exclude(id=b.id).first()
                if conflict:
                    conflict.code = conflict.code + f'_temp_{b.id}'
                    conflict.save()
                
                b.name = target_name
                b.code = target_code
                b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_room_qr_code'),
    ]

    operations = [
        migrations.RunPython(fix_buildings),
    ]
