# Generated by Django on 2026-07-21 03:51

from django.db import migrations
import uuid

def create_sample_rooms(apps, schema_editor):
    Building = apps.get_model('api', 'Building')
    Room = apps.get_model('api', 'Room')
    Meter = apps.get_model('api', 'Meter')
    
    # Define sample rooms for each building code
    samples = {
        '1': [1, 2, 3, 4, 5, 6, 7],
        '2': [1, 2, 3, 4, 5, 6, 7],
        '3': [101, 102, 201, 202, 301, 401, 501]
    }
    
    for b_code, room_numbers in samples.items():
        building = Building.objects.filter(code=b_code).first()
        if not building:
            continue
            
        for rn in room_numbers:
            # Check if room already exists
            room = Room.objects.filter(building=building, room_number=rn).first()
            if not room:
                room = Room.objects.create(
                    building=building,
                    room_number=rn,
                    qr_code=f"{b_code}-{rn}"  # Simple standard QR
                )
            
            # Ensure it has a meter attached
            if not hasattr(room, 'meter') and not Meter.objects.filter(room=room).exists():
                Meter.objects.create(
                    room=room,
                    meter_serial=f"SN-{b_code}-{rn}-{str(uuid.uuid4())[:6]}",
                    connection_status='connected'
                )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20260721_0246'),
    ]

    operations = [
        migrations.RunPython(create_sample_rooms),
    ]
