# Generated by Django on 2026-07-21 04:27

from django.db import migrations

def remove_sample_rooms(apps, schema_editor):
    Building = apps.get_model('api', 'Building')
    Room = apps.get_model('api', 'Room')
    
    # Define sample rooms to remove for each building code
    samples = {
        '1': [1, 2, 3, 4, 5, 6, 7],
        '2': [1, 2, 3, 4, 5, 6, 7],
        '3': [101, 102, 201, 202, 301, 401, 501]
    }
    
    for b_code, room_numbers in samples.items():
        building = Building.objects.filter(code=b_code).first()
        if not building:
            continue
            
        for rn in room_numbers:
            # Delete if it exists and has the dummy qr_code we used
            qr_pattern = f"{b_code}-{rn}"
            room = Room.objects.filter(building=building, room_number=rn, qr_code=qr_pattern).first()
            if room:
                room.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20260721_0351'),
    ]

    operations = [
        migrations.RunPython(remove_sample_rooms),
    ]
