# Generated by Django 5.2.16 on 2026-07-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20260721_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('period_type', models.CharField(choices=[('half_month', 'نصف شهري'), ('month', 'شهري'), ('year', 'سنوي')], max_length=20)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('total_kwh_consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_station_admin', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_electricity_committee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_student_committee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense_other_debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_reports', to='api.user')),
            ],
            options={
                'db_table': 'archive_reports',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
