# Generated by Django 5.2.16 on 2026-07-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_archivereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_overdue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمدة'), ('paid', 'مدفوعة')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualmeteraction',
            name='action_type',
            field=models.CharField(choices=[('connect', 'توصيل'), ('disconnect', 'فصل')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manualmeteraction',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('left', 'غادر')], db_index=True, default='active', max_length=10),
        ),
    ]
